// Static portfolio data — replace with real projects or Sanity CMS content

export const portfolioProjects = [
  {
    id: 'nexus-rebrand',
    title: 'Nexus Capital Rebrand',
    category: 'Branding',
    tags: ['branding'],
    thumbnail: null,
    color: '#E94560',
    bgGradient: 'from-[#E94560]/20 to-[#0D0D0D]',
    metric: '+340% brand recall',
    metricLabel: 'Brand Awareness',
    challenge: 'Nexus Capital had built a billion-dollar portfolio but their brand looked like a 2005 PowerPoint deck. They needed an identity that could command boardrooms and attract premium clients.',
    approach: 'We conducted 3 weeks of stakeholder interviews, competitor landscape analysis, and brand archetype mapping. The result: a bold "Precision Power" concept — sharp geometrics, deep navy, and a custom wordmark that communicates strength and intelligence.',
    outcome: 'Brand recall increased by 340% in post-launch surveys. Three major institutional clients cited the new identity as a key decision factor. The pitch deck redesign alone closed $12M in new investments.',
    tools: ['Illustrator', 'InDesign', 'Figma'],
  },
  {
    id: 'lumina-motion',
    title: 'Lumina — Brand Film',
    category: 'Video',
    tags: ['video'],
    thumbnail: null,
    color: '#F5A623',
    bgGradient: 'from-[#F5A623]/20 to-[#0D0D0D]',
    metric: '2.4M organic views',
    metricLabel: 'Reach',
    challenge: 'A DTC wellness brand needed a hero video that could compete with Nike and Apple-level production — on a startup budget. The film needed to feel premium, emotional, and shareable.',
    approach: 'Shot over 2 days with a lean 4-person crew using RED cinema cameras and natural lighting. Scripted around a "quiet strength" narrative. Post-production in DaVinci Resolve with custom color grade and original score commissioned from a Berlin composer.',
    outcome: '2.4M organic views in the first month across platforms. 38% increase in conversion rate on the landing page where the film was embedded. Nominated for two regional marketing awards.',
    tools: ['Premiere Pro', 'After Effects', 'DaVinci Resolve'],
    isVideo: true,
  },
  {
    id: 'archi-ui',
    title: 'ArchiSpace — Design System',
    category: 'UI',
    tags: ['ui'],
    thumbnail: null,
    color: '#E94560',
    bgGradient: 'from-[#E94560]/15 to-[#0D0D0D]',
    metric: '-60% design-to-dev time',
    metricLabel: 'Efficiency Gain',
    challenge: 'A PropTech startup had 4 product teams using 4 different component libraries. This caused UI inconsistency, duplicated effort, and 3-month feature cycles.',
    approach: 'Audited all existing components, interviewed 12 developers and designers, then built a comprehensive design system in Figma — 120 components, 8 color modes, full motion spec, and Storybook integration.',
    outcome: 'Design-to-dev handoff time dropped by 60%. First major feature shipped using the system went from concept to production in 3 weeks (previously 3 months). The system won a Design Excellence award.',
    tools: ['Figma', 'Storybook', 'Tokens Studio'],
  },
  {
    id: 'verde-web',
    title: 'Verde Organics — Web',
    category: 'Web',
    tags: ['web'],
    thumbnail: null,
    color: '#22c55e',
    bgGradient: 'from-[#22c55e]/15 to-[#0D0D0D]',
    metric: '+180% online revenue',
    metricLabel: 'E-commerce Growth',
    challenge: 'An organic skincare brand had a Shopify store converting at 0.8% — below industry average. They needed a complete rebuild that reflected their premium positioning.',
    approach: 'Custom WooCommerce build with bespoke product filtering, ingredient storytelling pages, and a "skin quiz" funnel. Integrated with Klaviyo for post-purchase flows and implemented LCP optimizations for sub-2s load times.',
    outcome: 'Conversion rate jumped from 0.8% to 3.2% (4x). Online revenue grew 180% in the first quarter post-launch. Page load time improved from 5.8s to 1.4s.',
    tools: ['WordPress', 'WooCommerce', 'Figma', 'Klaviyo'],
  },
  {
    id: 'forge-automation',
    title: 'Forge Agency — Automation',
    category: 'Automation',
    tags: ['automation'],
    thumbnail: null,
    color: '#8b5cf6',
    bgGradient: 'from-[#8b5cf6]/15 to-[#0D0D0D]',
    metric: '40hrs/week saved',
    metricLabel: 'Team Efficiency',
    challenge: 'A 12-person marketing agency was losing 40+ hours per week to manual tasks: CRM updates, invoice generation, client reporting, and social scheduling.',
    approach: 'Mapped all manual workflows across 4 departments. Built 23 interconnected automations in n8n and Make, integrating HubSpot, Notion, Stripe, and 6 social platforms. Included error monitoring and Slack alerting.',
    outcome: '40+ hours per week recovered. Invoice processing time went from 45 mins to 3 mins. Team reported 94% satisfaction with the new workflow. ROI achieved in 6 weeks.',
    tools: ['n8n', 'Make', 'Zapier', 'HubSpot'],
  },
  {
    id: 'kola-brand',
    title: 'Kola — Food Brand Launch',
    category: 'Branding',
    tags: ['branding'],
    thumbnail: null,
    color: '#F5A623',
    bgGradient: 'from-[#F5A623]/15 to-[#0D0D0D]',
    metric: 'Listed in 200+ stores',
    metricLabel: 'Retail Presence',
    challenge: 'A new functional beverage brand needed packaging, identity, and launch materials to compete with established players in a crowded category.',
    approach: 'Developed a full brand world: naming strategy validation, custom logotype, packaging for 4 SKUs, brand guidelines, and a complete social media system. Collaborated with a packaging printer for sustainable material selection.',
    outcome: 'Listed in 200+ retail stores in the first 3 months. Featured in 4 industry publications. The packaging design won a regional packaging excellence award. $2M raised in seed funding with the brand deck.',
    tools: ['Illustrator', 'InDesign', 'Photoshop', 'Dimension'],
  },
];
